# Copy this file to a new file `config.yaml`.
#
# You must modify the following:
#
#    production:
#        sumaserver:
#            db:
#                host: host location of your mysql database
#                dbname: suma mysql database name
#                user: suma mysql **application** account name
#                pword: suma mysql **application** account password
#                port: mysql port number
#            log:
#                path: path to log directory
#                name: sumaserver.log
#
#  * Be sure that the log directory specified in `sumaserver:log:path`
#  both exists and is **writable by the web server**.

production:
    sumaserver:
        # Database Connection
        db:
            host: localhost
            platform: Pdo_Mysql
            dbname: suma
            user: DB_USERNAME
            pword: DB_PASSWORD
            port: 3306
        # Log
        # e.g. sumaserver.log.path = /var/www/app/sumaserver/service/logs/
        log:
            path:
            name: sumaserver.log
        # Admin Login
        admin:
            user: admin
            pass: admin
    # Query Server
    queryserver:
        db:
            limit: 10000

development:
    _extends: production
    sumaserver:
        # Database Connection
        db:
            dbname: sumadev
        # Log
        # e.g. sumaserver.log.path = /var/www/app/sumaserver/service/logs/
        log:
            path:
