production:
    sumaserver:
        # Database Connection
        db:
            host: localhost
            platform: Pdo_Mysql
            dbname: suma
            user: DB_USERNAME
            pword: DB_PASSWORD
            port: 3306
        # Log
        # e.g. sumaserver.log.path = /var/www/app/sumaserver/service/logs/
        log:
            path:
            name: sumaserver.log
        # Admin Login
        admin:
            user: admin
            pass: admin
    # Query Server
    queryserver:
        db:
            limit: 10000

development:
    _extends: production
    sumaserver:
        # Database Connection
        db:
            dbname: sumadev
        # Log
        # e.g. sumaserver.log.path = /var/www/app/sumaserver/service/logs/
        log:
            path:
