language: node_js
node_js:
  - "4"
  - "0.12"
script: npm install && npm test
before_install:
  - npm install -g grunt-cli
  - gem install bundler
  - cd analysis && bundle install
notifications:
  email:
    - jmcasden@ncsu.edu
    - bddavids@ncsu.edu
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a200c25b0cbac74e2b9e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
matrix:
  allow_failures:
    - node_js: "5"
