site_name: Suma
site_url: http://cazzerson.github.io/Suma
theme: readthedocs
theme_dir: custom_theme
repo_url: https://github.com/cazzerson/Suma/releases
include_next_prev: false
pages:
- [index.md, Overview]
- [quickstart.md, Quickstart]
- [installation.md, Installation]
- [troubleshooting.md, Troubleshooting]
- [logs.md, Logs]
- [queryserver.md, Queryserver]
- [developer.md, Developer]
- [upgrade_1.0.md, Upgrade 1.0]
- [upgrade_2.0.md, Upgrade 2.0]

