site_name: Suma
site_url: http://suma-project.github.io/Suma
theme: readthedocs
repo_url: https://github.com/suma-project/Suma
include_next_prev: false
pages:
- [index.md, Overview]
- [quickstart.md, Quickstart]
- [installation.md, Installation]
- [troubleshooting.md, Troubleshooting]
- [faq.md, Frequently Asked Questions]
- [logs.md, Logs]
- [queryserver.md, Queryserver]
- [developer.md, Developer]
- [upgrade_1.0.md, Upgrade 1.0]
- [upgrade_2.0.md, Upgrade 2.0]
